2019-07-18T13:45:48|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:/Users/MurthyLab/Desktop/AntCam-master/main_interface.py", line 49, in <module>
    app = AntCamApp(sys.argv)
  File "C:\Users\MurthyLab\Anaconda3\lib\site-packages\ScopeFoundry\base_app.py", line 332, in __init__
    self.setup()
  File "C:/Users/MurthyLab/Desktop/AntCam-master/main_interface.py", line 34, in setup
    self.add_measurement(SelinaTraining(self))
  File "C:\Users\MurthyLab\Anaconda3\lib\site-packages\ScopeFoundry\measurement.py", line 93, in __init__
    self.setup()
  File "C:\Users\MurthyLab\Desktop\AntCam-master\AntCamMS\Selina_Contingency.py", line 133, in setup
    self.wide_cam.settings.frame_rate.update_value(8)
AttributeError: 'LQCollection' object has no attribute 'frame_rate'

