2019-07-18T13:52:45|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\MurthyLab\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 208, in enable_connection
    raise err
  File "C:\Users\MurthyLab\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 204, in enable_connection
    self.connect()
  File "C:\Users\MurthyLab\Desktop\AntCam-master\AntCamHW\flircam\camera_hw.py", line 21, in connect
    self.dev=CameraDev(self.settings.camera_id)
  File "C:\Users\MurthyLab\Desktop\AntCam-master\AntCamHW\flircam\camera_dev.py", line 15, in __init__
    self.cap = cv2.VideoCapture(self.camera_id)
TypeError: an integer is required (got type LoggedQuantity)

